### ISSUE TITLE
Error al acceder a la raiz de la api

### ISSUE THREAD

**Issue by ghost** [DiegoMGar/hackairethon#5]
Cuando se accede a la raíz de la api obtengo el siguiente error:

`
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
    at ServerResponse.end (_http_outgoing.js:697:13)
    at app.get (C:\Users\vicent.llinares\hackairethon\backend\dist\main.js:19:9)
    at Layer.handle [as handle_request] (C:\Users\vicent.llinares\hackairethon\backend\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\vicent.llinares\hackairethon\backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\vicent.llinares\hackairethon\backend\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\vicent.llinares\hackairethon\backend\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\vicent.llinares\hackairethon\backend\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\vicent.llinares\hackairethon\backend\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\vicent.llinares\hackairethon\backend\node_modules\express\lib\router\index.js:275:10)
    at cors (C:\Users\vicent.llinares\hackairethon\backend\node_modules\cors\lib\index.js:188:7)
`

**Comment by diekotto** [comment]
Has hecho `npm i` ?

**Comment by ghost** [comment]
Sí. Estoy haciendo el websocket para el chat en el backend y obtengo el mismo error al intentar el handshake con el front.

**Comment by diekotto** [comment]
El commit #6 arregla este problema, tenía el end para establecer el error y al refactorizar no cambié **end** por **send**. En mergear se debería arreglar.

**Comment by diekotto** [comment]
Cerrada por #6
